ALTER TABLE "AudioTrack"
ADD COLUMN "type" TEXT NOT NULL DEFAULT 'Training',
ADD COLUMN "orderToListen" INTEGER NOT NULL DEFAULT 1;

ALTER TABLE "UserProgress"
ADD COLUMN "isMyProgram" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "timesToListened" INTEGER NOT NULL DEFAULT 1;
